### ISSUE TITLE
[USER STORY] Eslint And Prettier Configured Consistently

### ISSUE THREAD

**Issue by osbornesec** [osbornesec/claudeviz#15]
---
story_id: STORY-1.6
epic: EPIC-01
persona: Developer (Jordan)
dependencies: ["STORY-1.5"]
---

# Target User Story

- [ ] **[STORY-1.6] User Story:** As a Developer (Jordan), I want ESLint and Prettier configured consistently, so that all team members follow the same code style.
- **Priority**: High
- **Story Points**: 3

## Objective & Success Criteria

Configure ESLint and Prettier with comprehensive rules that enforce consistent code style across the entire monorepo.

## Key Technical Constraints & References

You MUST adhere to the specifications in `.ai/docs/arch/00_ARCHITECTURAL_VISION.md`.
You MUST use the technologies specified in `.ai/docs/arch/02_TECHNOLOGY_STACK.md`.
You MUST follow the guidelines in `.ai/docs/DEVELOPER-GUIDELINES.md`.

## Quality Gates & Non-Functional Requirements

- All new functions, classes, and types MUST include TSDoc comments.
- The generated code MUST pass all linting rules as defined in `.eslintrc.js` and `prettier.config.js`.
- There MUST BE NO hardcoded secrets or "magic numbers"; use constants or environment variables.
- Performance MUST meet the targets outlined in `.ai/docs/arch/04_NON_FUNCTIONAL_REQUIREMENTS.md`.

### Step 1: Environment Pre-flight Check
Verify that `pnpm`, `node`, `tsc`, and `jest` are available in the environment. If any are missing, report the missing dependency and STOP.

### Step 2: Update Epic State
Check if the parent Epic file (`EPIC-01*.md`) is in the `.ai/product-backlog/todo/` directory. If so, move it to `.ai/product-backlog/in-progress/`. If it is already in progress, do nothing.

#### 3.a) RED: Write a Failing Test
Based on the User Story's Acceptance Criteria, identify the smallest, next piece of unimplemented functionality:

1. ESLint configuration with TypeScript support
2. Prettier formatting rules setup
3. Integration with VS Code and other editors
4. Workspace-aware configuration

Write focused unit tests for each piece of functionality before implementation.

#### 3.b) GREEN: Write Minimal Code to Pass
Write the absolute minimum amount of production code necessary to make the failing tests pass.
Do not add any extra logic or features beyond what is required to pass the test.

#### 3.c) REFACTOR: Improve the Code
With the safety of passing tests, review and improve:
- Code structure and clarity
- Performance optimizations
- Security considerations
- Compliance with Quality Gates

#### 3.d) REPEAT:
Continue the TDD cycle until all Acceptance Criteria are fully implemented and tested.

### Step 4: Final Validation
Run the full test suite for the affected package to ensure no regressions have been introduced.

### Step 5: Definition of Failure
If any test fails unexpectedly during this process, STOP. Report the failure, the test that failed, and the context. Proceed to fix the issue before continuing.

### Step 6: Create Pull Request (Final Step)
Upon successful completion of all testing, your final action is to create a Pull Request.

**Branch Name**: `feature/story-1-6-eslint-and-prettier-configured-consistently`

**PR Title**: `feat(EPIC-01): ESLint and Prettier configured consistently`

**PR Body**:
```markdown
### Implements
- Closes STORY-1.6

### Description
[Brief summary of the implementation]

### Implementation Details
[Key technical decisions made during the TDD process]

### Testing
- Added comprehensive unit tests following TDD methodology
- All functionality was developed test-first
- Tests cover edge cases and error conditions

### Changelog Entry
- [feat] ESLint and Prettier configured consistently
```

**CRITICAL**: Do not mark the story as complete in the backlog file. This will be done by a separate process after the PR is merged.

**Comment by osbornesec** [comment]
# ESLint and Prettier Configuration Guide

This comment provides comprehensive documentation and patterns for implementing ESLint and Prettier configuration across all packages with seamless integration, automated formatting, and code quality enforcement.

## ESLint Configuration with TypeScript Support

### 1. Root ESLint Configuration (eslint.config.js)

```javascript
// eslint.config.js
import { defineConfig } from "eslint/config";
import js from "@eslint/js";
import tsEslint from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import prettierConfig from "eslint-config-prettier";
import globals from "globals";

export default defineConfig([
  // Base configuration for all files
  js.configs.recommended,
  
  // TypeScript configuration
  {
    files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        project: ["./tsconfig.json", "./packages/*/tsconfig.json"],
        tsconfigRootDir: ".",
      },
      globals: {
        ...globals.node,
        ...globals.browser,
        ...globals.es2022,
      },
    },
    plugins: {
      "@typescript-eslint": tsEslint,
    },
    rules: {
      // TypeScript-specific rules
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      "@typescript-eslint/no-non-null-assertion": "warn",
      "@typescript-eslint/prefer-const": "error",
      "@typescript-eslint/no-var-requires": "error",
      
      // Code quality rules
      "prefer-const": "error",
      "no-var": "error",
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "eqeqeq": ["error", "always"],
      "curly": ["error", "all"],
      "no-throw-literal": "error",
      "prefer-template": "error",
    },
  },
  
  // React/JSX configuration
  {
    files: ["packages/web/**/*.tsx", "packages/web/**/*.jsx"],
    languageOptions: {
      globals: {
        ...globals.browser,
        React: "readonly",
      },
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    rules: {
      "react/react-in-jsx-scope": "off", // Next.js doesn't require React import
      "react/prop-types": "off", // Using TypeScript for prop validation
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
    },
  },
  
  // Node.js specific configuration
  {
    files: ["packages/api/**/*.ts", "packages/cli/**/*.ts"],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
    rules: {
      "no-console": "off", // Allow console in Node.js packages
      "node/no-process-exit": "error",
      "node/no-path-concat": "error",
    },
  },
  
  // Test files configuration
  {
    files: ["**/*.test.ts", "**/*.test.tsx", "**/__tests__/**/*.ts"],
    languageOptions: {
      globals: {
        ...globals.jest,
        ...globals.node,
      },
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "no-console": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
    },
  },
  
  // Configuration files
  {
    files: ["*.config.js", "*.config.ts", ".eslintrc.js"],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
    rules: {
      "@typescript-eslint/no-var-requires": "off",
      "no-console": "off",
    },
  },
  
  // Ignore patterns
  {
    ignores: [
      "**/dist/**",
      "**/build/**",
      "**/node_modules/**",
      "**/.next/**",
      "**/coverage/**",
      "**/*.min.js",
      "**/generated/**",
    ],
  },
  
  // Prettier integration (must be last)
  prettierConfig,
]);
```

### 2. Package-Specific ESLint Configurations

#### API Package (packages/api/eslint.config.js)
```javascript
// packages/api/eslint.config.js
import { defineConfig } from "eslint/config";
import baseConfig from "../../eslint.config.js";

export default defineConfig([
  ...baseConfig,
  {
    files: ["src/**/*.ts"],
    rules: {
      // API-specific rules
      "@typescript-eslint/explicit-function-return-type": ["error", {
        allowExpressions: true,
        allowTypedFunctionExpressions: true,
      }],
      "no-console": ["warn", { allow: ["info", "warn", "error"] }],
      
      // Security rules for API
      "security/detect-object-injection": "warn",
      "security/detect-non-literal-regexp": "warn",
    },
  },
]);
```

#### Web Package (packages/web/eslint.config.js)
```javascript
// packages/web/eslint.config.js
import { defineConfig } from "eslint/config";
import baseConfig from "../../eslint.config.js";
import reactHooks from "eslint-plugin-react-hooks";
import react from "eslint-plugin-react";
import jsxA11y from "eslint-plugin-jsx-a11y";

export default defineConfig([
  ...baseConfig,
  {
    files: ["src/**/*.tsx", "src/**/*.jsx"],
    plugins: {
      react,
      "react-hooks": reactHooks,
      "jsx-a11y": jsxA11y,
    },
    settings: {
      react: {
        version: "detect",
      },
    },
    rules: {
      // React rules
      "react/jsx-uses-react": "off",
      "react/react-in-jsx-scope": "off",
      "react/jsx-uses-vars": "error",
      "react/jsx-key": "error",
      "react/no-array-index-key": "warn",
      "react/no-unused-prop-types": "error",
      
      // React Hooks rules
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      
      // Accessibility rules
      "jsx-a11y/alt-text": "error",
      "jsx-a11y/anchor-has-content": "error",
      "jsx-a11y/aria-role": "error",
      "jsx-a11y/click-events-have-key-events": "warn",
    },
  },
]);
```

## Prettier Configuration

### 1. Root Prettier Configuration (prettier.config.js)

```javascript
// prettier.config.js
/**
 * @see https://prettier.io/docs/configuration
 * @type {import("prettier").Config}
 */
const config = {
  // Code formatting
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  quoteProps: "as-needed",
  
  // JSX formatting
  jsxSingleQuote: true,
  bracketSameLine: false,
  bracketSpacing: true,
  
  // Trailing commas
  trailingComma: "es5",
  
  // Arrow functions
  arrowParens: "avoid",
  
  // Range formatting
  rangeStart: 0,
  rangeEnd: Infinity,
  
  // Parser
  requirePragma: false,
  insertPragma: false,
  proseWrap: "preserve",
  
  // HTML formatting
  htmlWhitespaceSensitivity: "css",
  
  // End of line
  endOfLine: "lf",
  
  // Embedded language formatting
  embeddedLanguageFormatting: "auto",
  
  // Single attribute per line
  singleAttributePerLine: false,
  
  // File overrides for specific patterns
  overrides: [
    {
      files: "*.json",
      options: {
        printWidth: 80,
        tabWidth: 2,
      },
    },
    {
      files: "*.md",
      options: {
        printWidth: 80,
        proseWrap: "always",
        tabWidth: 2,
      },
    },
    {
      files: "*.yaml",
      options: {
        tabWidth: 2,
        singleQuote: false,
      },
    },
    {
      files: ["package.json", "**/package.json"],
      options: {
        tabWidth: 2,
        useTabs: false,
      },
    },
    {
      files: "*.css",
      options: {
        singleQuote: false,
      },
    },
  ],
};

export default config;
```

### 2. Prettier Ignore Configuration (.prettierignore)

```
# Dependencies
node_modules/
**/node_modules/

# Build outputs
dist/
build/
**/dist/
**/build/
.next/
**/.next/

# Generated files
coverage/
**/coverage/
*.min.js
*.min.css
**/generated/

# Configuration files that shouldn't be formatted
pnpm-lock.yaml
yarn.lock
package-lock.json

# Documentation that should preserve formatting
CHANGELOG.md
**/CHANGELOG.md

# Environment files
.env
.env.local
.env.*.local

# IDE files
.vscode/
.idea/

# OS files
.DS_Store
Thumbs.db
```

## Package.json Scripts Configuration

### 1. Root Package.json Scripts

```json
{
  "scripts": {
    "lint": "eslint . --ext .ts,.tsx,.js,.jsx",
    "lint:fix": "eslint . --ext .ts,.tsx,.js,.jsx --fix",
    "lint:check": "eslint . --ext .ts,.tsx,.js,.jsx --max-warnings 0",
    "format": "prettier --write .",
    "format:check": "prettier --check .",
    "format:changed": "prettier --write $(git diff --name-only --cached)",
    "code-quality": "pnpm run lint:check && pnpm run format:check && pnpm run typecheck",
    "fix-all": "pnpm run lint:fix && pnpm run format",
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*.{ts,tsx,js,jsx}": [
      "eslint --fix",
      "prettier --write"
    ],
    "*.{json,md,yml,yaml,css,scss}": [
      "prettier --write"
    ],
    "package.json": [
      "prettier --write",
      "sort-package-json"
    ]
  }
}
```

### 2. Package-Specific Scripts

```json
{
  "scripts": {
    "lint": "eslint src --ext .ts,.tsx",
    "lint:fix": "eslint src --ext .ts,.tsx --fix",
    "format": "prettier --write src",
    "format:check": "prettier --check src"
  }
}
```

## IDE Integration

### 1. VS Code Settings (.vscode/settings.json)

```json
{
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "editor.formatOnPaste": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": "always",
    "source.organizeImports": "always"
  },
  "eslint.workingDirectories": [
    "./packages/api",
    "./packages/web",
    "./packages/cli",
    "./packages/shared"
  ],
  "eslint.options": {
    "extensions": [".ts", ".tsx", ".js", ".jsx"]
  },
  "typescript.preferences.organizeImports": true,
  "files.exclude": {
    "**/node_modules": true,
    "**/dist": true,
    "**/.next": true
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[markdown]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.wordWrap": "on"
  }
}
```

### 2. VS Code Extensions (.vscode/extensions.json)

```json
{
  "recommendations": [
    "esbenp.prettier-vscode",
    "dbaeumer.vscode-eslint",
    "bradlc.vscode-tailwindcss",
    "ms-vscode.vscode-typescript-next",
    "editorconfig.editorconfig"
  ]
}
```

## Pre-commit Hooks with Husky

### 1. Husky Configuration (.husky/pre-commit)

```bash
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running pre-commit quality checks..."

# Check for merge conflict markers
if grep -r "<<<<<<< \|>>>>>>> \|=======" --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" .; then
  echo "❌ Merge conflict markers found. Please resolve conflicts."
  exit 1
fi

# Run lint-staged for automatic fixes
echo "🔧 Running lint-staged..."
pnpm lint-staged

# Run type checking (fast, no emit)
echo "🔍 Type checking..."
pnpm typecheck

# Check for TODO/FIXME in staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(ts|tsx|js|jsx)$' || true)
if [ ! -z "$STAGED_FILES" ]; then
  TODO_COUNT=$(echo "$STAGED_FILES" | xargs grep -l "TODO\|FIXME" | wc -l || echo "0")
  if [ $TODO_COUNT -gt 0 ]; then
    echo "⚠️  Warning: Found $TODO_COUNT file(s) with TODO/FIXME comments"
    echo "$STAGED_FILES" | xargs grep -n "TODO\|FIXME" || true
  fi
fi

echo "✅ Pre-commit checks completed!"
```

### 2. Commit Message Hook (.husky/commit-msg)

```bash
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Conventional commit format validation
commit_regex='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: .{1,80}'

if ! grep -qE "$commit_regex" "$1"; then
  echo "❌ Invalid commit message format!"
  echo ""
  echo "Format: type(scope): description"
  echo ""
  echo "Types:"
  echo "  feat:     A new feature"
  echo "  fix:      A bug fix"
  echo "  docs:     Documentation only changes"
  echo "  style:    Changes that do not affect the meaning of the code"
  echo "  refactor: A code change that neither fixes a bug nor adds a feature"
  echo "  perf:     A code change that improves performance"
  echo "  test:     Adding missing tests or correcting existing tests"
  echo "  build:    Changes that affect the build system or external dependencies"
  echo "  ci:       Changes to CI configuration files and scripts"
  echo "  chore:    Other changes that don't modify src or test files"
  echo "  revert:   Reverts a previous commit"
  echo ""
  echo "Example: feat(auth): add user authentication"
  exit 1
fi

echo "✅ Commit message format is valid"
```

## CI/CD Integration

### 1. GitHub Actions Workflow (.github/workflows/code-quality.yml)

```yaml
name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  HUSKY: 0  # Disable Husky in CI

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run ESLint
        run: pnpm run lint:check
        
      - name: Check Prettier formatting
        run: pnpm run format:check
        
      - name: Run TypeScript type checking
        run: pnpm run typecheck
        
      - name: Run tests
        run: pnpm test
        
      - name: Upload ESLint results
        uses: github/super-linter@v4
        if: always()
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_JAVASCRIPT_ES: true
```

### 2. Auto-fix Workflow (.github/workflows/auto-fix.yml)

```yaml
name: Auto-fix Code Issues

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-fix:
    name: Auto-fix ESLint and Prettier Issues
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run ESLint with auto-fix
        run: pnpm run lint:fix
        
      - name: Run Prettier
        run: pnpm run format
        
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style: auto-fix ESLint and Prettier issues'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
```

## Advanced Configuration Features

### 1. Custom ESLint Rules

```javascript
// tools/eslint-rules/prefer-typed-responses.js
module.exports = {
  meta: {
    type: "suggestion",
    docs: {
      description: "Enforce typed API responses",
      category: "Best Practices",
    },
    schema: [],
  },
  create(context) {
    return {
      CallExpression(node) {
        if (
          node.callee.property &&
          node.callee.property.name === "json" &&
          node.arguments.length > 0
        ) {
          // Check for typed response pattern
          const sourceCode = context.getSourceCode();
          const text = sourceCode.getText(node);
          
          if (!text.includes("ApiResponse<")) {
            context.report({
              node,
              message: "API responses should use typed ApiResponse<T> interface",
            });
          }
        }
      },
    };
  },
};
```

### 2. Prettier Plugin Integration

```javascript
// prettier.config.js with plugins
const config = {
  // ... base config
  plugins: [
    "prettier-plugin-organize-imports",
    "prettier-plugin-tailwindcss",
    "@trivago/prettier-plugin-sort-imports",
  ],
  
  // Plugin-specific options
  importOrder: [
    "^react",
    "^next",
    "^@/",
    "^[./]",
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  
  // Tailwind CSS class sorting
  tailwindFunctions: ["clsx", "cn"],
};
```

## Troubleshooting Guide

### 1. Common ESLint Issues

```bash
# Clear ESLint cache
npx eslint --cache --cache-location .eslintcache --fix .

# Debug ESLint configuration
npx eslint --print-config src/index.ts

# Check what files ESLint is processing
npx eslint --debug src/
```

### 2. Common Prettier Issues

```bash
# Check Prettier configuration resolution
npx prettier --find-config-path src/index.ts

# Debug Prettier formatting
npx prettier --check --debug-check src/index.ts

# Test Prettier with specific parser
npx prettier --parser typescript src/index.ts
```

### 3. Monorepo Integration Issues

```javascript
// eslint.config.js - Handle monorepo paths
export default defineConfig([
  {
    languageOptions: {
      parserOptions: {
        project: [
          "./tsconfig.json",
          "./packages/*/tsconfig.json",
        ],
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
]);
```

## Benefits of This Configuration

- **Consistent Code Style**: Unified formatting across all packages and team members
- **Early Error Detection**: Comprehensive linting rules catch issues before runtime
- **Automated Fixing**: Auto-fix capabilities for most style and simple logic issues
- **IDE Integration**: Seamless development experience with real-time feedback
- **CI/CD Ready**: Automated quality checks in continuous integration
- **Monorepo Optimized**: Proper configuration inheritance and package-specific rules
- **Performance Optimized**: Caching and incremental checking for faster execution
- **Security Focused**: Security-related linting rules for API and client code

## Key Features Used

### ESLint:
- **Flat Configuration**: Modern ESLint configuration format
- **TypeScript Integration**: Full TypeScript support with type-aware rules
- **Monorepo Support**: Package-specific configurations with inheritance
- **Custom Rules**: Project-specific linting rules
- **Performance**: Caching and incremental linting

### Prettier:
- **File-specific Overrides**: Different formatting rules for different file types
- **Plugin Integration**: Import sorting, Tailwind CSS class ordering
- **Editor Integration**: Seamless formatting on save
- **Ignore Patterns**: Comprehensive ignore configuration
- **Consistency**: Unified formatting across the entire codebase

This comprehensive setup ensures code quality, consistency, and developer productivity across the entire ClaudeViz monorepo.

---
*Documentation based on official ESLint and Prettier documentation and modern best practices for TypeScript monorepos.*
