### ISSUE TITLE
[USER STORY] Containerized Dev Environment

### ISSUE THREAD

**Issue by osbornesec** [osbornesec/claudeviz#4]
---
story_id: STORY-1.1
epic: EPIC-01
persona: Developer (Jordan)
dependencies: []
---

# Target User Story

- [ ] **[STORY-1.1] User Story:** As a Developer (Jordan), I want a fully containerized local development environment, so that I can run the entire stack with a single command and ensure consistency across the team.
- **Priority**: High
- **Story Points**: 8
- **Acceptance Criteria**:
  - **Given** I have cloned the repository and have Docker installed
  - **When** I run `docker-compose up`
  - **Then** all required services (PostgreSQL, Redis, API, web app) should start without errors
  - **And** I can connect to the local database on port 5432
  - **And** I can access the web application at http://localhost:3000
  - **And** I can access the API at http://localhost:4000/graphql
  - **And** all services have proper health checks that report healthy status

## Objective & Success Criteria

Implement a complete containerized development environment that allows any developer to spin up the entire ClaudeViz stack with a single Docker Compose command. Success is measured by:
- All services start successfully without manual intervention
- Health checks pass for all services
- Services are accessible on specified ports
- Database connectivity is established
- Zero configuration required beyond having Docker installed

## Key Technical Constraints & References

You MUST adhere to the specifications in `.ai/docs/arch/00_ARCHITECTURAL_VISION.md`.
You MUST use the technologies specified in `.ai/docs/arch/02_TECHNOLOGY_STACK.md`.
You MUST follow the guidelines in `.ai/docs/DEVELOPER-GUIDELINES.md`.

## Quality Gates & Non-Functional Requirements

- All new functions, classes, and types MUST include TSDoc comments.
- The generated code MUST pass all linting rules as defined in `.eslintrc.js` and `prettier.config.js`.
- There MUST BE NO hardcoded secrets or "magic numbers"; use constants or environment variables.
- Performance MUST meet the targets outlined in `.ai/docs/arch/04_NON_FUNCTIONAL_REQUIREMENTS.md`.
- Container startup time MUST be under 2 minutes on standard development hardware.
- All services MUST include proper logging and health check endpoints.

### Step 1: Environment Pre-flight Check
Verify that `pnpm`, `node`, `tsc`, and `jest` are available in the environment. If any are missing, report the missing dependency and STOP.

### Step 2: Update Epic State
Check if the parent Epic file (`EPIC-01*.md`) is in the `.ai/product-backlog/todo/` directory. If so, move it to `.ai/product-backlog/in-progress/`. If it is already in progress, do nothing.

#### 3.a) RED: Write a Failing Test
Based on the User Story's Acceptance Criteria, identify the smallest, next piece of unimplemented functionality:

First functionality: Docker Compose file existence and basic structure
- Write a test that verifies `docker-compose.yml` exists in the project root
- Test that the compose file defines the required services: postgres, redis, api, web
- Test that services expose correct ports
- Run the test and confirm it fails (file doesn't exist)

#### 3.b) GREEN: Write Minimal Code to Pass
Create the minimal `docker-compose.yml` file with:
- Basic service definitions for postgres, redis, api, web
- Correct port mappings
- Basic environment variables
- No optimization, just enough to pass the test

#### 3.c) REFACTOR: Improve the Code
Review and improve:
- Add proper health checks for all services
- Add volume mounts for persistence
- Add environment variable files
- Optimize for development workflow (hot reload, etc.)
- Ensure security best practices

#### 3.d) REPEAT:
Continue TDD cycle for:
1. PostgreSQL service configuration with proper credentials
2. Redis service configuration
3. API service with proper dependencies
4. Web application service
5. Health check implementations
6. Environment variable management
7. Development-specific optimizations

### Step 4: Final Validation
Run the complete test suite and verify:
- `docker-compose up` starts all services successfully
- All health checks pass
- Services are accessible on specified ports
- Database connection can be established
- No errors in service logs

### Step 5: Definition of Failure
If any test fails unexpectedly during this process, STOP. Report the failure, the test that failed, and the context. Proceed to fix the issue before continuing.

### Step 6: Create Pull Request (Final Step)
Upon successful completion of all testing, your final action is to create a Pull Request.

**Branch Name**: `feature/story-1-1-containerized-dev-environment`

**PR Title**: `feat(EPIC-01): Implement containerized local development environment`

**PR Body**:
```markdown
### Implements
- Closes STORY-1.1

### Description
Implements a complete Docker Compose setup for local development that spins up PostgreSQL, Redis, API, and web application services with a single command.

### Implementation Details
- Created docker-compose.yml with all required services
- Implemented health checks for service monitoring
- Added proper environment variable management
- Configured development-optimized settings for hot reload
- Added volume mounts for data persistence

### Testing
- Added integration tests for Docker Compose configuration validation
- Tested service startup and health check functionality
- Verified port accessibility and service communication
- All functionality developed test-first following TDD methodology

### Changelog Entry
- [feat] Added containerized local development environment with Docker Compose support
```

**CRITICAL**: Do not mark the story as complete in the backlog file. This will be done by a separate process after the PR is merged.

**Comment by osbornesec** [comment]
## 🐳 Docker Compose Development Environment - Context7 Documentation

Based on the requirements for a containerized development environment with PostgreSQL, Redis, API, and web app, here are proven patterns from Docker's official documentation:

### 📋 Multi-Service Development Setup

**Key Components Needed:**
- PostgreSQL database (port 5432)
- Redis cache
- GraphQL API (port 4000) 
- Web application (port 3000)

### 🔧 Recommended Docker Compose Structure

```yaml
services:
  # Web Application Service
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      api:
        condition: service_started
    environment:
      - NODE_ENV=development
      - API_URL=http://api:4000/graphql
    volumes:
      - ./:/app  # Live code reloading
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  # GraphQL API Service  
  api:
    build:
      context: ./packages/api
      target: development
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_DB=claudeviz
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./packages/api:/app
    secrets:
      - db-password

  # PostgreSQL Database
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=claudeviz
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - db-password

  # Redis Cache
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:

secrets:
  db-password:
    file: db/password.txt
```

### 🛠️ Development Best Practices

**Multi-Stage Dockerfile for API:**
```dockerfile
FROM node:18-alpine as base
WORKDIR /app
EXPOSE 4000

FROM base as development
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --include=dev
USER node
COPY . .
CMD npm run dev

FROM base as production
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev
USER node
COPY . .
CMD node src/index.js
```

### ⚡ Quick Start Commands

```bash
# Start all services
docker compose up --build

# Start with live reloading (Compose Watch)
docker compose watch

# Start specific services only
docker compose up db redis

# View logs
docker compose logs -f api
```

### 🔧 Development Features

- **Live Reloading**: Code changes sync automatically to containers
- **Health Checks**: Services wait for dependencies to be ready
- **Secrets Management**: Database passwords stored securely
- **Volume Persistence**: Database data survives container restarts
- **Service Dependencies**: Correct startup order guaranteed

**Source:** Docker Official Documentation - [Multi-container applications](https://docs.docker.com/guides/)
